services:
  postgres:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: db_ventas_users
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  app:
    image: vseddocker/users_microservicios:v1.4
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

volumes:
  pg-data:
