services:
  web:
    image: jason7217/microservicios_eventos:v1.4
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=DKJDHFDasdss1238/95222sdsdsd-*885sd9**
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=eventos_service.settings
      - POSTGRES_DB=eventos_db
      - POSTGRES_USER=eventos_user
      - POSTGRES_PASSWORD=eventos_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=eventos_db
      - POSTGRES_USER=eventos_user
      - POSTGRES_PASSWORD=eventos_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventos_user -d eventos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 